#!/usr/bin/env python3
"""1080p downloads of the clips and continuous runs on /lab/combined/.

Usage:
    python3 scripts/lab/encode_downloads.py /path/to/SGS \
        --limits ~/Downloads/anymal_limits_trimmed [--only ID ...] [--force]

The owner wants every video downloadable at a high enough resolution
(2026-10-08). This reuses encode_library.py's footage definitions without
changing it: its main() and lists give the same sources, cuts and ids, and
this swaps in encoders that write, instead of the page's 960 px files,

    public/lab/media/library/download/{id}.mp4
        up to 1920 px wide, 30 fps (ANYmal per-terrain clips keep their
        rate), H.264 high, CRF 20 with the bitrate capped, no audio;
        continuous runs at CRF 23 with a lower cap, so every file stays
        under the 25 MiB per-file limit of Cloudflare's static assets

then writes app/lab/_combined/downloads.ts, the ids, sizes and dimensions
the page offers. Skipped: the stand-ins, the single UR5e simulation runs
(the page shows the back-to-back pairs) and the earlier ANYmal D clips
(the page shows the per-terrain ones, and the earlier maze). Requires ffmpeg
and ffprobe. Existing outputs are kept unless --force.
"""

import importlib.util
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
DL = os.path.join(ROOT, "public", "lab", "media", "library", "download")
DATA = os.path.join(ROOT, "app", "lab", "_combined", "downloads.ts")

spec = importlib.util.spec_from_file_location("encode_library", os.path.join(HERE, "encode_library.py"))
lib = importlib.util.module_from_spec(spec)
spec.loader.exec_module(lib)

X264 = ["-c:v", "libx264", "-preset", "medium", "-profile:v", "high", "-pix_fmt", "yuv420p",
        "-movflags", "+faststart", "-an"]
CLIP = ["-crf", "20", "-maxrate", "8M", "-bufsize", "16M"]
RUN = ["-crf", "23", "-maxrate", "2.8M", "-bufsize", "5.6M"]
FIT = "crop=iw:min(ih\\,iw*9/16),scale='min(1920,iw)':-2"


def skip(ident):
    return (
        ident.startswith("standin-")
        or re.fullmatch(r"ur5e-sim-.+-\d+", ident) is not None
        or (ident.startswith("anymal-d-") and not ident.startswith("anymal-d-limit-")
            and ident != "anymal-d-maze")
    )


def clip_jobs(src, ident, trim=None, fps=30):
    if skip(ident):
        return []
    t = ["-ss", str(trim[0]), "-to", str(trim[1])] if trim else []
    out = os.path.join(DL, f"{ident}.mp4")
    vf = FIT + (f",fps={fps}" if fps else "")

    def go():
        # Clips longer than 30 s (the one-minute Franka run) get the
        # continuous runs' settings, to stay under 25 MiB.
        long = (trim[1] - trim[0]) if trim else lib.duration(src)
        lib.run([*t, "-i", src, "-vf", vf, *(RUN if long > 30 else CLIP), *X264, out])

    return [(out, go)]


def seq_jobs(root, task, a, b):
    ident = f"ur5e-sim-{task.replace('_', '-')}-seq"
    src = [os.path.join(root, "UR5e Sim", task, f"clip{n}", f"{task}_clip{n}_static_closeup.mp4")
           for n in (a, b)]
    out = os.path.join(DL, f"{ident}.mp4")
    f = ("[0]scale=1920:1080,setsar=1,fps=30[a];[1]scale=1920:1080,setsar=1,fps=30[b];"
         "[a][b]concat=n=2:v=1:a=0")
    return [(out, lambda: lib.run(["-i", src[0], "-i", src[1], "-filter_complex", f, *CLIP, *X264, out]))]


def run_jobs(root, ident, rel, speed):
    out = os.path.join(DL, f"{ident}.mp4")
    src = os.path.join(root, rel)
    return [(out, lambda: lib.run(["-i", src, "-vf", "scale='min(1920,iw)':-2,fps=30", *RUN, *X264, out]))]


def probe(path):
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height",
         "-of", "csv=p=0", path],
        capture_output=True, text=True, check=True,
    )
    w, h = r.stdout.strip().split(",")
    return int(w), int(h)


def main():
    os.makedirs(DL, exist_ok=True)
    lib.OUT = DL
    lib.clip_jobs = clip_jobs
    lib.seq_jobs = seq_jobs
    lib.run_jobs = run_jobs
    lib.pair_jobs = lambda *a, **k: []
    lib.reel_jobs = lambda *a, **k: []
    sys.argv = ["encode_library.py", *sys.argv[1:]]
    lib.main()
    # encode_library makes its own subfolders under OUT; none are used here.
    for d in ("clips", "clips-sm", "runs"):
        p = os.path.join(DL, d)
        if os.path.isdir(p) and not os.listdir(p):
            os.rmdir(p)

    rows = {}
    for name in sorted(os.listdir(DL)):
        if not name.endswith(".mp4"):
            continue
        path = os.path.join(DL, name)
        size = os.path.getsize(path)
        assert size < 25 * 1024 * 1024, f"{name} is {size / 2**20:.1f} MiB"
        w, h = probe(path)
        rows[name[:-4]] = {"w": w, "h": h, "mb": round(size / 1e6, 1)}
    with open(DATA, "w") as f:
        f.write(
            "// Generated by scripts/lab/encode_downloads.py. Do not edit by hand.\n"
            "// The clips the page offers as downloads: id -> width, height and size\n"
            "// (MB) of public/lab/media/library/download/{id}.mp4.\n\n"
            "export const DOWNLOADS: Record<string, { w: number; h: number; mb: number }> =\n"
            f"  {json.dumps(rows, indent=2)};\n"
        )
    print(f"wrote {os.path.relpath(DATA, ROOT)}: {len(rows)} downloads, "
          f"{sum(r['mb'] for r in rows.values()):.0f} MB", flush=True)


if __name__ == "__main__":
    main()
