// Generated by scripts/lab/encode_downloads.py. Do not edit by hand.
// The clips the page offers as downloads: id -> width, height and size
// (MB) of public/media/library/download/{id}.mp4.

export const DOWNLOADS: Record<string, { w: number; h: number; mb: number }> = {
  "anymal-c-limit-balancing-beam": {
    w: 1920,
    h: 1080,
    mb: 1.3,
  },
  "anymal-c-limit-climbing-box": {
    w: 1920,
    h: 1080,
    mb: 2.4,
  },
  "anymal-c-limit-contour": {
    w: 1920,
    h: 1080,
    mb: 2.7,
  },
  "anymal-c-limit-floating-island": {
    w: 1920,
    h: 1080,
    mb: 2.2,
  },
  "anymal-c-limit-gap": {
    w: 1920,
    h: 1080,
    mb: 1.4,
  },
  "anymal-c-limit-inverted-slope": {
    w: 1920,
    h: 1080,
    mb: 1.1,
  },
  "anymal-c-limit-jump-box": {
    w: 1920,
    h: 1080,
    mb: 1.6,
  },
  "anymal-c-limit-pit": {
    w: 1920,
    h: 1080,
    mb: 0.7,
  },
  "anymal-c-limit-radiating-beam-offset": {
    w: 1920,
    h: 1080,
    mb: 1.8,
  },
  "anymal-c-limit-random-parallel-box": {
    w: 1920,
    h: 1080,
    mb: 1.5,
  },
  "anymal-c-limit-stairs": {
    w: 1920,
    h: 1080,
    mb: 1.8,
  },
  "anymal-c-limit-stepping-stones": {
    w: 1920,
    h: 1080,
    mb: 3.6,
  },
  "anymal-c-terrains": {
    w: 1920,
    h: 1080,
    mb: 2.8,
  },
  "anymal-d-limit-balancing-beam": {
    w: 1920,
    h: 1080,
    mb: 1.2,
  },
  "anymal-d-limit-climbing-box": {
    w: 1920,
    h: 1080,
    mb: 2.5,
  },
  "anymal-d-limit-contour": {
    w: 1920,
    h: 1080,
    mb: 2.6,
  },
  "anymal-d-limit-floating-island": {
    w: 1920,
    h: 1080,
    mb: 2.0,
  },
  "anymal-d-limit-gap": {
    w: 1920,
    h: 1080,
    mb: 1.1,
  },
  "anymal-d-limit-inverted-slope": {
    w: 1920,
    h: 1080,
    mb: 1.0,
  },
  "anymal-d-limit-jump-box": {
    w: 1920,
    h: 1080,
    mb: 1.1,
  },
  "anymal-d-limit-pit": {
    w: 1920,
    h: 1080,
    mb: 0.8,
  },
  "anymal-d-limit-radiating-beam-offset": {
    w: 1920,
    h: 1080,
    mb: 1.6,
  },
  "anymal-d-limit-random-parallel-box": {
    w: 1920,
    h: 1080,
    mb: 1.3,
  },
  "anymal-d-limit-stairs": {
    w: 1920,
    h: 1080,
    mb: 1.8,
  },
  "anymal-d-limit-stepping-stones": {
    w: 1920,
    h: 1080,
    mb: 2.1,
  },
  "anymal-d-maze": {
    w: 1920,
    h: 1080,
    mb: 2.7,
  },
  "franka-sim-nut-1": {
    w: 1920,
    h: 1080,
    mb: 1.0,
  },
  "franka-sim-nut-1m-full": {
    w: 1920,
    h: 1080,
    mb: 7.1,
  },
  "franka-sim-nut-1m": {
    w: 1920,
    h: 1080,
    mb: 3.2,
  },
  "franka-sim-nut-2": {
    w: 1920,
    h: 1080,
    mb: 2.4,
  },
  "franka-sim-nut-3": {
    w: 1920,
    h: 1080,
    mb: 1.1,
  },
  "run-anymal-c": {
    w: 1920,
    h: 1080,
    mb: 14.9,
  },
  "run-franka-sim-nut": {
    w: 1920,
    h: 1080,
    mb: 4.7,
  },
  "run-ur5e-real-gear-mesh": {
    w: 1920,
    h: 1080,
    mb: 21.6,
  },
  "ur5e-real-gear-mesh-1": {
    w: 1920,
    h: 1080,
    mb: 7.1,
  },
  "ur5e-real-gear-mesh-2": {
    w: 1920,
    h: 1080,
    mb: 4.7,
  },
  "ur5e-real-gear-mesh-3": {
    w: 1920,
    h: 1080,
    mb: 9.8,
  },
  "ur5e-real-gear-mesh-4": {
    w: 1920,
    h: 1080,
    mb: 4.4,
  },
  "ur5e-real-gear-mesh-5": {
    w: 1920,
    h: 1080,
    mb: 5.1,
  },
  "ur5e-real-gear-spin": {
    w: 1920,
    h: 1080,
    mb: 5.1,
  },
  "ur5e-real-nut-1": {
    w: 1920,
    h: 1080,
    mb: 12.4,
  },
  "ur5e-real-nut-3": {
    w: 1920,
    h: 1080,
    mb: 12.1,
  },
  "ur5e-real-nut-4": {
    w: 1920,
    h: 1080,
    mb: 6.2,
  },
  "ur5e-real-nut-5": {
    w: 1920,
    h: 1080,
    mb: 10.9,
  },
  "ur5e-real-rod-1": {
    w: 1920,
    h: 1080,
    mb: 3.4,
  },
  "ur5e-real-rod-2": {
    w: 1920,
    h: 1080,
    mb: 1.5,
  },
  "ur5e-real-rod-3": {
    w: 1920,
    h: 1080,
    mb: 4.2,
  },
  "ur5e-real-rod-4": {
    w: 1920,
    h: 1080,
    mb: 7.3,
  },
  "ur5e-real-rod-5": {
    w: 1920,
    h: 1080,
    mb: 3.1,
  },
  "ur5e-real-rod-6": {
    w: 1920,
    h: 1080,
    mb: 7.4,
  },
  "ur5e-sim-bnc-seq": {
    w: 1920,
    h: 1080,
    mb: 3.0,
  },
  "ur5e-sim-gear-mesh-seq": {
    w: 1920,
    h: 1080,
    mb: 2.3,
  },
  "ur5e-sim-nut-seq": {
    w: 1920,
    h: 1080,
    mb: 3.1,
  },
  "ur5e-sim-rectangular-peg-seq": {
    w: 1920,
    h: 1080,
    mb: 2.2,
  },
  "ur5e-sim-rod-seq": {
    w: 1920,
    h: 1080,
    mb: 1.9,
  },
  "ur5e-sim-waterproof-seq": {
    w: 1920,
    h: 1080,
    mb: 3.2,
  },
};
