// Generated by scripts/lab/encode_learning.py from Patrick's SGS
// learning-progress bundle (2026-10-07). Do not edit by hand.
//
// Per UR5e task: one fixed reset (a task configuration), 64 trials
// per training checkpoint. rows: every measured checkpoint (it), its
// successes (s) and 95% Wilson interval (lo, hi); `separate` marks
// rows from a separate evaluation batch. clips: output frames of the
// footage per checkpoint. CURVE: the SGS rule's weight relative to its
// peak for 0..64 successes of 64 (an illustration of the rule, not
// measured sampling frequency).

export type LearningRow = {
  it: number;
  s: number;
  lo: number;
  hi: number;
  separate?: boolean;
};
export type LearningTask = {
  key: string;
  title: string;
  src: string;
  poster: string;
  fps: number;
  frames: number;
  trials: number;
  clips: { it: number; start: number; end: number }[];
  rows: LearningRow[];
};

export const RULE = {
  gps_target: 0.5,
  gps_kappa: 1.0,
  gps_temperature: 2.0,
  gps_eps: 0.0001,
};

export const CURVE: number[] = [
  0.1421, 0.4989, 0.5904, 0.6506, 0.6961, 0.7329, 0.7637, 0.7902, 0.8134, 0.834,
  0.8523, 0.8687, 0.8836, 0.8971, 0.9093, 0.9205, 0.9307, 0.9399, 0.9483,
  0.9559, 0.9628, 0.9691, 0.9747, 0.9796, 0.984, 0.9878, 0.9911, 0.9938, 0.9961,
  0.9978, 0.999, 0.9998, 1.0, 0.9998, 0.999, 0.9978, 0.9961, 0.9938, 0.9911,
  0.9878, 0.984, 0.9796, 0.9747, 0.9691, 0.9628, 0.9559, 0.9483, 0.9399, 0.9307,
  0.9205, 0.9093, 0.8971, 0.8836, 0.8687, 0.8523, 0.834, 0.8134, 0.7902, 0.7637,
  0.7329, 0.6961, 0.6506, 0.5904, 0.4989, 0.1421,
];

export const TASKS: LearningTask[] = [
  {
    key: "nut",
    title: "Nut on bolt",
    src: "/lab/media/library/learning/nut.mp4",
    poster: "/lab/media/library/learning/nut.jpg",
    fps: 30,
    frames: 775,
    trials: 64,
    clips: [
      {
        it: 2800,
        start: 0,
        end: 119,
      },
      {
        it: 4000,
        start: 120,
        end: 284,
      },
      {
        it: 4200,
        start: 285,
        end: 449,
      },
      {
        it: 4600,
        start: 450,
        end: 614,
      },
      {
        it: 5400,
        start: 615,
        end: 774,
      },
    ],
    rows: [
      {
        it: 0,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
        separate: true,
      },
      {
        it: 1000,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
        separate: true,
      },
      {
        it: 1800,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
        separate: true,
      },
      {
        it: 2800,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 3800,
        s: 9,
        lo: 0.0758,
        hi: 0.2462,
      },
      {
        it: 4000,
        s: 27,
        lo: 0.3087,
        hi: 0.5439,
      },
      {
        it: 4200,
        s: 51,
        lo: 0.6829,
        hi: 0.8773,
      },
      {
        it: 4400,
        s: 52,
        lo: 0.7003,
        hi: 0.8894,
      },
      {
        it: 4600,
        s: 57,
        lo: 0.791,
        hi: 0.946,
      },
      {
        it: 5400,
        s: 59,
        lo: 0.8298,
        hi: 0.9662,
      },
    ],
  },
  {
    key: "rod",
    title: "Rod in hole",
    src: "/lab/media/library/learning/rod.mp4",
    poster: "/lab/media/library/learning/rod.jpg",
    fps: 30,
    frames: 599,
    trials: 64,
    clips: [
      {
        it: 400,
        start: 0,
        end: 119,
      },
      {
        it: 600,
        start: 120,
        end: 284,
      },
      {
        it: 800,
        start: 285,
        end: 444,
      },
      {
        it: 1000,
        start: 445,
        end: 598,
      },
    ],
    rows: [
      {
        it: 0,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 200,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 400,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 600,
        s: 40,
        lo: 0.5025,
        hi: 0.7333,
      },
      {
        it: 800,
        s: 61,
        lo: 0.871,
        hi: 0.9839,
      },
      {
        it: 1000,
        s: 62,
        lo: 0.893,
        hi: 0.9914,
      },
      {
        it: 1400,
        s: 61,
        lo: 0.871,
        hi: 0.9839,
      },
      {
        it: 2000,
        s: 63,
        lo: 0.9167,
        hi: 0.9972,
      },
      {
        it: 3000,
        s: 60,
        lo: 0.85,
        hi: 0.9754,
      },
    ],
  },
  {
    key: "gear-mesh",
    title: "Gear mesh",
    src: "/lab/media/library/learning/gear-mesh.mp4",
    poster: "/lab/media/library/learning/gear-mesh.jpg",
    fps: 30,
    frames: 471,
    trials: 64,
    clips: [
      {
        it: 200,
        start: 0,
        end: 119,
      },
      {
        it: 400,
        start: 120,
        end: 284,
      },
      {
        it: 600,
        start: 285,
        end: 410,
      },
      {
        it: 1200,
        start: 411,
        end: 470,
      },
    ],
    rows: [
      {
        it: 0,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 200,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 400,
        s: 39,
        lo: 0.4869,
        hi: 0.7194,
      },
      {
        it: 600,
        s: 54,
        lo: 0.7357,
        hi: 0.9129,
      },
      {
        it: 800,
        s: 60,
        lo: 0.85,
        hi: 0.9754,
      },
      {
        it: 1000,
        s: 60,
        lo: 0.85,
        hi: 0.9754,
      },
      {
        it: 1200,
        s: 61,
        lo: 0.871,
        hi: 0.9839,
      },
      {
        it: 1600,
        s: 60,
        lo: 0.85,
        hi: 0.9754,
      },
      {
        it: 2400,
        s: 63,
        lo: 0.9167,
        hi: 0.9972,
      },
    ],
  },
  {
    key: "bnc",
    title: "BNC connector",
    src: "/lab/media/library/learning/bnc.mp4",
    poster: "/lab/media/library/learning/bnc.jpg",
    fps: 30,
    frames: 686,
    trials: 64,
    clips: [
      {
        it: 400,
        start: 0,
        end: 119,
      },
      {
        it: 1200,
        start: 120,
        end: 284,
      },
      {
        it: 1800,
        start: 285,
        end: 449,
      },
      {
        it: 2600,
        start: 450,
        end: 567,
      },
      {
        it: 7200,
        start: 568,
        end: 685,
      },
    ],
    rows: [
      {
        it: 0,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 400,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 1000,
        s: 4,
        lo: 0.0246,
        hi: 0.15,
      },
      {
        it: 1200,
        s: 14,
        lo: 0.135,
        hi: 0.3343,
      },
      {
        it: 1400,
        s: 22,
        lo: 0.2392,
        hi: 0.466,
      },
      {
        it: 1600,
        s: 28,
        lo: 0.3229,
        hi: 0.5591,
      },
      {
        it: 1800,
        s: 40,
        lo: 0.5025,
        hi: 0.7333,
      },
      {
        it: 2000,
        s: 48,
        lo: 0.6318,
        hi: 0.8399,
      },
      {
        it: 2600,
        s: 53,
        lo: 0.7179,
        hi: 0.9012,
      },
      {
        it: 7200,
        s: 59,
        lo: 0.8298,
        hi: 0.9662,
      },
    ],
  },
  {
    key: "waterproof",
    title: "Waterproof connector",
    src: "/lab/media/library/learning/waterproof.mp4",
    poster: "/lab/media/library/learning/waterproof.jpg",
    fps: 30,
    frames: 677,
    trials: 64,
    clips: [
      {
        it: 800,
        start: 0,
        end: 119,
      },
      {
        it: 1000,
        start: 120,
        end: 284,
      },
      {
        it: 1200,
        start: 285,
        end: 449,
      },
      {
        it: 1600,
        start: 450,
        end: 546,
      },
      {
        it: 2400,
        start: 547,
        end: 676,
      },
    ],
    rows: [
      {
        it: 0,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 600,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 800,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 1000,
        s: 21,
        lo: 0.2257,
        hi: 0.45,
      },
      {
        it: 1200,
        s: 44,
        lo: 0.5661,
        hi: 0.7877,
      },
      {
        it: 1400,
        s: 46,
        lo: 0.5987,
        hi: 0.8141,
      },
      {
        it: 1600,
        s: 51,
        lo: 0.6829,
        hi: 0.8773,
      },
      {
        it: 1800,
        s: 52,
        lo: 0.7003,
        hi: 0.8894,
      },
      {
        it: 2400,
        s: 57,
        lo: 0.791,
        hi: 0.946,
      },
    ],
  },
  {
    key: "rectangular-peg",
    title: "Rectangular peg",
    src: "/lab/media/library/learning/rectangular-peg.mp4",
    poster: "/lab/media/library/learning/rectangular-peg.jpg",
    fps: 30,
    frames: 606,
    trials: 64,
    clips: [
      {
        it: 1200,
        start: 0,
        end: 119,
      },
      {
        it: 1400,
        start: 120,
        end: 284,
      },
      {
        it: 1800,
        start: 285,
        end: 411,
      },
      {
        it: 2400,
        start: 412,
        end: 523,
      },
      {
        it: 8200,
        start: 524,
        end: 605,
      },
    ],
    rows: [
      {
        it: 0,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 400,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 900,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 1000,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 1200,
        s: 0,
        lo: 0.0,
        hi: 0.0566,
      },
      {
        it: 1400,
        s: 9,
        lo: 0.0758,
        hi: 0.2462,
      },
      {
        it: 1600,
        s: 28,
        lo: 0.3229,
        hi: 0.5591,
      },
      {
        it: 1800,
        s: 31,
        lo: 0.3663,
        hi: 0.6042,
      },
      {
        it: 2000,
        s: 42,
        lo: 0.534,
        hi: 0.7608,
      },
      {
        it: 2400,
        s: 57,
        lo: 0.791,
        hi: 0.946,
      },
      {
        it: 2800,
        s: 57,
        lo: 0.791,
        hi: 0.946,
      },
      {
        it: 8200,
        s: 62,
        lo: 0.893,
        hi: 0.9914,
      },
    ],
  },
];
